// If the politics cards don't exist in the collection, they will be populated from this list

if(Politics.find().count() === 0) {
  Politics.insert(
    {
      politicsCards : {
        dictatorship : {
          zero : [
          "War Weariness.\nLose 3 Francs if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities.\nLose 1 Franc for every city beyond your initial territory that you currently occupy.",
          "Major Riot in Capital.\nLose 2 Francs.\nMay substitute 4 supplies (if available in one of your original cities) if you wish.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 2 Francs.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories behind your original borders (if you have any).",
          "Briefcase Bomb Plot.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nBlitzkrieg orders are no longer available to you in the subsequent turn.",
          "Major Coup Attempt!\nThe subsequent fighting consumes all of the new production - supplies and units - from one of the cities in your home territories (chosen randomly).",
          "Air Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Oligarchs Assert Power.\nUnless you have conquered and control two full economic zones beyond your initial borders (as of drawing this card), you must pay the oligarchs (the bank) 15 Francs the next time you conquer a new territory (after a successful invasion, during that combat phase).\nThis card lasts until canceled by some other card or the action is fulfilled.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nMilitary units in your home territories all participate in the hunt for the killer - and use one supply each (drawn from anywhere in your home territories; you choose).",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Proclaims Independence!\nA full economic zone outside your home territories, chosen randomly, becomes neutral and obtains 5 neutral infantry placed in some random territory of that province.\nThe League of Nations will vote for control of those armies immediately; it requires only 3 Francs total contribution to control.\nIf League fails to vote to secure the armies, remove both the neutral infantry and three of your own units in the economic zone from the board.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising!\nChoose randomly among cities you have captured.\nIf the city is garrisoned with less than 3 units, it proclaims neutrality and adds 3 infantry.\nThe League of Nations votes immediately for control.\nYour units evacuate to an adjacent territory that you control (if impossible, your units are lost).\nIf the League fails to provide 3 Francs, the freedom fighters disappear from the map.",
          "Guerilla\'s Plot to Aid Invaders.\nKeep this card out until canceled otherwise.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats.",
          "Low Morale.\nEnlistees seek to dodge the draft.\nInfantry and armor costs increase by 1 Pound for this next allocation phase.",
          "Political Corruption Damages Your Supply Chain.\nIn every location you have ordered new supplies produced, 3 less supplies are actually produced than ordered in this turn.",
          "Weapons Program Corruption.\nYour nuclear scientists have been lying to you.\nYour nuclear progress is actually... 0, including any production ordered this turn.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 2 (added) GDP points from all of your fully conquered economic zones.",
          "Navy Avoids Battle.\nYour poorly paid admirals all choose \"hide\" for all combat phases during the next turn rather than risk their lives for you.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most one combat card.",
          "Massive Supply Theft!\nRemove ten supplies from your stocks currently on the board.\nWhile you shoot those responsible, unfortunately it is impossible to locate the lost goods.",
          "Low Infantry Morale.\nWith idiots like you in charge, the war is hopeless.\nWho wants to be the last to die in a lost cause?\nFully supplied infantry in the next turn fight at (1 attack, 2 defense); unsupplied infantry fight at (0 attack, 1 defense).",
          "Bagdad Bob.\nIf you have lost any of your starting territory, lose 15 Francs for the embarrassment."
          ],

          thirty : [
          "Swim a mile in a river to demonstrate your health.\nObtain 2 Francs.",
          "Drink champagne for breakfast.\nNothing happens.",
          "Opposition figure caught in bed with \"dead girl or live boy.\"\nGain 5 Francs.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 1 Franc.",
          "Loot Conquered Territory.\nFor every full economic zone you have conquered, get 5 Francs.\nWipes away any negative political cards still in effect.",
          "Briefcase Bomb Plot Fails.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nPay 1 Franc to smooth things over.\nWipes away any negative political cards still in effect.",
          "Major Coup Attempt Caught!\nObtain two additional Francs from selling the plotter\'s stolen art collections.\nWipes away any negative political cards still in effect.",
          "Air Chief Found Incompetent.\nLose 2 supplies from anywhere (you choose).",
          "Oligarchs Support Regime with technical assistance.\nGain 2 supplies (place anywhere) and 3 Francs.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nGives you an excuse to round up the usual suspects.\nObtain 1 Franc.",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Movement Betrayed.\nAll attempts to destabilize your government fail; nothing happens.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Pro-regime fanatics undermine the domestic life of the democracies.\nObtain 3 Francs for every Democracy still in the game.",
          "Guerillas Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Youth program success!\nObtain an extra infantry unit that may be placed in any of your original cities (immediately).",
          "Foreign Loot Supports War Effort.\nFor every full economic zone you have conquered, obtain 3 extra supplies (place anywhere you control, immediately).",
          "Weapons Program Espionage.\nRandomly choose among the Democracies.\nObtain at least their level of atomic research.",
          "Youth program encourages fanaticism in the army.\nDefending (all order types) land units fight at an additional +1 for this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYou fire them - but it costs you some to smooth things over, make them Field Marshals, and shunt them out of the way.\nPay 3 Francs.",
          "All Quiet on the Western Front.\nNothing happens.",
          "Held Military Review.\nObtain 1 Franc.",
          "Impressive Party Rally.\nObtain 2 Francs."
          ],

          twenty : [
          "War Weariness.\nLose 1 Franc if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities easily contained.\nNothing happens.",
          "Opposition figure caught in bed with \"dead girl or live boy.\"\nGain 5 Francs.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 1 Franc.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories beyond your original borders (if you have any).",
          "Briefcase Bomb Plot Fails.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nPay 1 Franc to smooth things over.\nWipes away any negative political cards still in effect.",
          "Major Coup Attempt Caught!\nObtain two additional Francs from selling the plotter\'s stolen art collections.\nWipes away any negative political cards still in effect.",
          "Air Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Key opposition figure \"has accident.\"\nGain 3 Francs.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nGives you an excuse to round up the usual suspects.\nObtain 1 Franc.",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Movement Betrayed.\nAll attempts to destabilize your government fail; nothing happens.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising Crushed!\nYou lose one supply (from anywhere, your choice) but obtain 3 Francs.",
          "Guerilla\'s Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Youth program success!\nObtain an extra infantry unit that may be placed in any of your original cities (immediately).",
          "Foreign Loot Supports War Effort.\nFor every full economic zone you have conquered, obtain 3 extra supplies (place anywhere you control, immediately).",
          "Weapons Program Espionage.\nRandomly choose among the Democracies.\nObtain at least their level of atomic research.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most three combat cards.",
          "All Quiet on the Western Front.\nNothing happens.",
          "Held Military Review.\nObtain 1 Franc.",
          "Impressive Party Rally.\nObtain 2 Francs."
          ],

          ten : [
          "War Weariness.\nLose 3 Francs if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities.\nLose 1 Franc for every city beyond your initial territory that you currently occupy.",
          "Major Riot in Capital.\nLose 2 Francs.\nMay substitute 4 supplies (if available in one of your original cities) if you wish.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 2 Francs.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories behind your original borders (if you have any).",
          "Briefcase Bomb Plot.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nBlitzkrieg orders are no longer available to you on this turn.",
          "Major Coup Attempt!\nThe subsequent fighting consumes all of the new production - supplies and units - from one of the cities in your home territories (chosen randomly).",
          "Air Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Oligarchs Assert Power.\nUnless you have conquered and control two full economic zones beyond your initial borders (as of drawing this card), you must pay the oligarchs (the bank) 10 Francs the next time you conquer a new territory (after a successful invasion, during that combat phase).\nThis card lasts until canceled by some other card or the action is fulfilled.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nMilitary units in your home territories all participate in the hunt for the killer - and use one supply each (drawn from anywhere in your home territories; you choose).",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Proclaims Independence!\nA full economic zone outside your home territories, chosen randomly, becomes neutral and obtains 5 neutral infantry placed in some random territory of that province.\nThe League of Nations will vote for control of those armies immediately; it requires only 3 Francs total contribution to control.\nIf League fails to vote to secure the armies, remove both the neutral infantry and three of your own units in the economic zone from the board.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising!\nChoose randomly among cities you have captured.\nIf the city is garrisoned with either no units or only one unit, it proclaims neutrality and adds 3 infantry.\nThe League of Nations votes immediately for control.\nYour unit evacuates to an adjacent territory that you control (if impossible, your unit is lost).\nIf the League fails to provide 3 Francs, the freedom fighters disappear from the map.",
          "Guerilla\'s Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Low Morale.\nEnlistees seek to dodge the draft.\nInfantry and armor costs increase by 1 Pound for this next allocation phase.",
          "Political Corruption Damages Your Supply Chain.\nIn every location you have ordered new supplies produced, 2 less supplies are actually produced than ordered in this turn.",
          "Weapons Program Corruption.\nYour nuclear scientists have been lying to you.\nYour nuclear progress is actually half what you thought it was, including any production ordered this turn.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most one combat card.",
          "Massive Supply Theft!\nRemove 5 supplies from your stocks currently on the board.\nWhile you shoot those responsible, unfortunately it is impossible to locate the lost goods.",
          "Low Infantry Morale.\nWith idiots like you in charge, the war is hopeless.\nWho wants to be the last to die in a lost cause?\nFully supplied infantry in the next turn fight at (1 attack, 2 defense); unsupplied infantry fight at (0 attack, 1 defense).",
          "Bagdad Bob.\nIf you have lost any of your starting territory, lose 10 Francs for the embarrassment."
          ]
        },
        democracy: {
          ten : [
          "No elections held this year.\nDomestic tranquility.\nObtain 3 Francs.",
          "Minor corruption trials related to weapons programs.\nLose 2 Francs to hush it up unless you had more atomic research (at the end of your previous turn) than any other player.",
          "Success buys tranquility.\nIf you have full possession of more economic zones than with which you began the game, obtain 1 Franc.\nOtherwise, lose 1 Franc.",
          "Retrospective voting.\nIf GDP increased over the turn, face no negative political consequences.\nOtherwise, pay 5 Francs.",
          "Peace dividends.\nIf you took no casualties over the last year, obtain 5 Francs.\nOtherwise, pay 5 Francs.",
          "Peace Party obtain majority.\nMilitary units abroad not returned within your original boundaries by the end of the following winter are disbanded.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists obtain majority.\nYour units may not fight in allied combinations with dictatorships for two full turns (display this card over that entire period; may be canceled by subsequent political cards).",
          "Anti-Imperialists demand recognition of national independence movements.\nAny territories acquired through the action of the league of nations on your part must be returned to independence and neutrality - including any units currently in those territories that belong to you.\nAllied units are evacuated to their nearest exit point or sold back to the bank for 1 Franc each.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year.",
          "Peace Party defeats defense budget.\nYou may not spend anything on military units, supplies, or atomic development in this upcoming turn.\nYou must spend 30% of your budget on politics.\nYou must spend as much as you can on economic development.\nAny unspent GDP (due to costs of development) is simply lost.",
          "Hawks defeat budget.\nYou must spend your entire budget on military units and supplies.",
          "Government gridlock.\nYou repeat your expenditures by category from the previous year (so, same amount for military units, supplies, politics, atomic research, and development).\nAnything not obtainable is lost.",
          "The Coburn Committee seeks to eliminate waste, fraud, and abuse; you may not make any political spending for the next turn.\nAdditionally, lose 5 Francs.",
          "Payoffs to Tammany Hall.\nSpend 50 percent of your GDP on politics to obtain the 30% outcome - or lose 20 Francs at the end of the next turn.\nKeep this card out (decide privately).",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 10 Francs per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 20 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Force Exit from League of Nations.\nYou may not participate in the League of Nations for the next two turns.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the remainder of the game, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the remainder of the game, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Independence Vote Successful.\nOne of your economic zones (other than those with which you began the game with full control), chosen at random, votes for independence.\nAll units, supplies, and development in that territory becomes part of an independent neutral country.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 1 in the next turn (if fully supplied) and a combat value of .5 if unsupplied.",
          "Anti-War Protestors prevent recruitment.\nAll infantry units slated to be produced this turn refuse to enlist and are disbanded."
          ],

          thirty : [
          "No elections held this year.\nObtain an additional 5 Francs.",
          "Form national government.\nIn the next political cycle, obtain 30% payout in Francs but retain the GDP and draw no political cards.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 5 additional Francs.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 1 Franc.",
          "Peace Dividends.\nIf you took no casualties over the last turn, obtain 10 additional Francs.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 3 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Propaganda Victory.\nFor every vote at the League of Nations this turn, each of your Francs counts as two.",
          "Anti-communists ask you to form dictatorship.\nObtain one-time payout of 15 Francs and then play the rest of the game as a dictator if you choose.\nOtherwise, obtain a one-time payout of 20 Francs.",
          "Peace Party defeats defense budget.\nYou may not purchase any armor or heavy fleets in this turn.",
          "Navy advocates insist on the construction of one heavy fleet.\nIf you pay 2 Francs now, you may produce the fleet at a 5 pound discount.\nIf you do not produce the fleet by the end of the next turn, pay 1 Franc.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.\n",
          "The Coburn Committee suspends operation because Senator Coburn dies of a heart attack.\nObtain 3 Francs.",
          "War enthusiasm lowers infantry and armor costs by 1 pound per unit this turn.",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 1 Franc per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next turn, lose 5 Francs.",
          "Isolationists Wish to Exit from League of Nations.\nIf you leave the League of Nations for the next two turns, collect 5 Francs.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the next turn, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 1 Franc for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the next turn, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors shot by national guard.\nPay 1 Franc.",
          "Anti-War Protestors increase the cost of recruitment.\nInfantry and Armor units cost an additional pound this turn."
          ],

          twenty : [
          "No elections held this year.\nObtain an additional 3 Francs.",
          "Peace Party offers conditional support.\nIf in your last turn you purchased no additional atomic research, obtain 3 Francs.\nOtherwise, nothing happens.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 5 additional Francs.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 1 Franc.",
          "Peace Dividends.\nIf you took no casualties over the last turn, obtain 7 additional Francs.\nOtherwise, lose 1 Franc.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 3 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Propaganda Victory.\nFor every vote at the League of Nations this turn, each of your Francs counts as two.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year unless you pay 2 Francs for the turn (now).",
          "Peace Party defeats defense budget.\nYou may not purchase any armor or heavy fleets in this turn.",
          "Navy advocates insist on the construction of one heavy fleet.\nIf you do not comply, or cannot comply, lose 2 Francs.\nKeep this card on the table.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.",
          "The Coburn Committee finds waste, fraud, and abuse.\nYou may not spend more than 10% on politics in the next year and you must pay 4 Francs immediately to the bank.",
          "War enthusiasm lowers infantry cost by 1 pound per unit this turn.",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 1 Franc per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 10 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Wish to Exit from League of Nations.\nIf you leave the League of Nations for the next two turns, collect 5 Francs.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the next turn, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the next turn, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 2 in the next turn (if fully supplied) and a combat value of 1 if unsupplied.",
          "Anti-War Protestors increase the cost of recruitment.\nInfantry and Armor units cost an additional pound this turn."
          ],

          ten : [
          "No elections held this year.\nObtain an additional 3 Francs.",
          "Peace Party offers conditional support.\nIf in your last turn you purchased no additional atomic research, obtain 2 Francs.\nOtherwise, nothing happens.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 1 additional Franc.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 2 Francs.",
          "Peace Dividends.\nIf you took no casualties over the last tun, obtain 5 additional Francs.\nOtherwise, lose 2 Francs.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 5 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Anti-Imperialists demand recognition of national independence movements.\nAny territories acquired through the action of the league of nations on your part must be returned to independence and neutrality if the league votes on their independence and pays at least 1 Franc per unit in the territories.\nYour units and allied units are evacuated to their nearest exit point or sold back to the bank for 1 Franc each.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year.",
          "Peace Party defeats defense budget.\nYou may not purchase any additional military units in the upcoming turn although you may purchase supplies.",
          "Hawks insist on the construction of two heavy fleets.\nYou must comply if your budget allows and you have port facilities.\nIf you do not have port facilities, pay 2 Francs.\nIf you have ports but your budget does not allow the construction of two heavy fleets, pay 5 Francs.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.",
          "The Coburn Committee finds waste, fraud, and abuse.\nYou may not spend more than 10% on politics in the next year and you must pay 4 Francs immediately to the bank.",
          "Payoffs to Tammany Hall.\nSpend 50 percent of your GDP on politics to obtain the 30% outcome - or lose 5 Francs at the end of the next turn.\nKeep this card out (decide privately).",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 3 Francs per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 20 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Force Exit from League of Nations.\nYou may not participate in the League of Nations for the next two turns.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the remainder of the game, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the remainder of the game, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 1 in the next turn (if fully supplied) and a combat value of .5 if unsupplied.",
          "Anti-War Protestors prevent recruitment.\nAll infantry units slated to be produced this turn refuse to enlist and are disbanded."
          ]
        },
        dictatorship: {
          zero : [
          "War Weariness.\nLose 3 Francs if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities.\nLose 1 Franc for every city beyond your initial territory that you currently occupy.",
          "Major Riot in Capital.\nLose 2 Francs.\nMay substitute 4 supplies (if available in one of your original cities) if you wish.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 2 Francs.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories behind your original borders (if you have any).",
          "Briefcase Bomb Plot.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nBlitzkrieg orders are no longer available to you in the subsequent turn.",
          "Major Coup Attempt!\nThe subsequent fighting consumes all of the new production - supplies and units - from one of the cities in your home territories (chosen randomly).",
          "\nAir Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Oligarchs Assert Power.\nUnless you have conquered and control two full economic zones beyond your initial borders (as of drawing this card), you must pay the oligarchs (the bank) 15 Francs the next time you conquer a new territory (after a successful invasion, during that combat phase).\nThis card lasts until canceled by some other card or the action is fulfilled.\n",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nMilitary units in your home territories all participate in the hunt for the killer - and use one supply each (drawn from anywhere in your home territories; you choose).",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Proclaims Independence!\nA full economic zone outside your home territories, chosen randomly, becomes neutral and obtains 5 neutral infantry placed in some random territory of that province.\nThe League of Nations will vote for control of those armies immediately; it requires only 3 Francs total contribution to control.\nIf League fails to vote to secure the armies, remove both the neutral infantry and three of your own units in the economic zone from the board.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising!\nChoose randomly among cities you have captured.\nIf the city is garrisoned with less than 3 units, it proclaims neutrality and adds 3 infantry.\nThe League of Nations votes immediately for control.\nYour units evacuate to an adjacent territory that you control (if impossible, your units are lost).\nIf the League fails to provide 3 Francs, the freedom fighters disappear from the map.",
          "Guerilla\'s Plot to Aid Invaders.\nKeep this card out until canceled otherwise.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats.", "Low Morale.\nEnlistees seek to dodge the draft.\nInfantry and armor costs increase by 1 Pound for this next allocation phase.",
          "Political Corruption Damages Your Supply Chain.\nIn every location you have ordered new supplies produced, 3 less supplies are actually produced than ordered in this turn.",
          "Weapons Program Corruption.\nYour nuclear scientists have been lying to you.\nYour nuclear progress is actually... 0, including any production ordered this turn.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 2 (added) GDP points from all of your fully conquered economic zones.",
          "Navy Avoids Battle.\nYour poorly paid admirals all choose \"hide\" for all combat phases during the next turn rather than risk their lives for you.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most one combat card.",
          "Massive Supply Theft!\nRemove ten supplies from your stocks currently on the board.\nWhile you shoot those responsible, unfortunately it is impossible to locate the lost goods.",
          "Low Infantry Morale.\nWith idiots like you in charge, the war is hopeless.\nWho wants to be the last to die in a lost cause?\nFully supplied infantry in the next turn fight at (1 attack, 2 defense); unsupplied infantry fight at (0 attack, 1 defense).",
          "Bagdad Bob.\nIf you have lost any of your starting territory, lose 15 Francs for the embarrassment."
          ],

          thirty : [
          "Swim a mile in a river to demonstrate your health.\nObtain 2 Francs.",
          "Drink champagne for breakfast.\nNothing happens.",
          "Opposition figure caught in bed with \"dead girl or live boy.\"\nGain 5 Francs.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 1 Franc.",
          "Loot Conquered Territory.\nFor every full economic zone you have conquered, get 5 Francs.\nWipes away any negative political cards still in effect.",
          "Briefcase Bomb Plot Fails.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nPay 1 Franc to smooth things over.\nWipes away any negative political cards still in effect.",
          "Major Coup Attempt Caught!\nObtain two additional Francs from selling the plotter\'s stolen art collections.\nWipes away any negative political cards still in effect.",
          "Air Chief Found Incompetent.\nLose 2 supplies from anywhere (you choose).",
          "Oligarchs Support Regime with technical assistance.\nGain 2 supplies (place anywhere) and 3 Francs.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nGives you an excuse to round up the usual suspects.\nObtain 1 Franc.",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Movement Betrayed.\nAll attempts to destabilize your government fail; nothing happens.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Pro-regime fanatics undermine the domestic life of the democracies.\nObtain 3 Francs for every Democracy still in the game.",
          "Guerillas Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Youth program success!\nObtain an extra infantry unit that may be placed in any of your original cities (immediately).",
          "Foreign Loot Supports War Effort.\nFor every full economic zone you have conquered, obtain 3 extra supplies (place anywhere you control, immediately).",
          "Weapons Program Espionage.\nRandomly choose among the Democracies.\nObtain at least their level of atomic research.",
          "Youth program encourages fanaticism in the army.\nDefending (all order types) land units fight at an additional +1 for this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYou fire them - but it costs you some to smooth things over, make them Field Marshals, and shunt them out of the way.\nPay 3 Francs.",
          "All Quiet on the Western Front.\nNothing happens.\n",
          "Held Military Review.\nObtain 1 Franc.",
          "Impressive Party Rally.\nObtain 2 Francs."
          ],

          twenty : [
          "War Weariness.\nLose 1 Franc if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities easily contained.\nNothing happens.",
          "Opposition figure caught in bed with \"dead girl or live boy.\"\nGain 5 Francs.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 1 Franc.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories beyond your original borders (if you have any).",
          "Briefcase Bomb Plot Fails.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nPay 1 Franc to smooth things over.\nWipes away any negative political cards still in effect.",
          "Major Coup Attempt Caught!\nObtain two additional Francs from selling the plotter\'s stolen art collections.\nWipes away any negative political cards still in effect.",
          "Air Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Key opposition figure \"has accident.\"\nGain 3 Francs.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nGives you an excuse to round up the usual suspects.\nObtain 1 Franc.",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Movement Betrayed.\nAll attempts to destabilize your government fail; nothing happens.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising Crushed!\nYou lose one supply (from anywhere, your choice) but obtain 3 Francs.",
          "Guerilla\'s Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Youth program success!\nObtain an extra infantry unit that may be placed in any of your original cities (immediately).",
          "Foreign Loot Supports War Effort.\nFor every full economic zone you have conquered, obtain 3 extra supplies (place anywhere you control, immediately).",
          "Weapons Program Espionage.\nRandomly choose among the Democracies.\nObtain at least their level of atomic research.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most three combat cards.",
          "All Quiet on the Western Front.\nNothing happens.",
          "Held Military Review.\nObtain 1 Franc.",
          "Impressive Party Rally.\nObtain 2 Francs."
          ],

          ten : [
          "War Weariness.\nLose 3 Francs if you do not possess all of your original territories.\nOtherwise, nothing happens.",
          "Disturbances in Captured Cities.\nLose 1 Franc for every city beyond your initial territory that you currently occupy.",
          "Major Riot in Capital.\nLose 2 Francs.\nMay substitute 4 supplies (if available in one of your original cities) if you wish.",
          "Show Trial Poorly Received.\nThe witnesses were too sympathetic.\nPay 2 Francs.",
          "Minor Underground activity.\nRemove two supplies (you choose) from territories behind your original borders (if you have any).",
          "Briefcase Bomb Plot.\nYou are disabled in a bombing at headquarters and subsequently execute a top general.\nBlitzkrieg orders are no longer available to you on this turn.",
          "Major Coup Attempt!\nThe subsequent fighting consumes all of the new production - supplies and units - from one of the cities in your home territories (chosen randomly).",
          "Air Chief Defects.\nRemove one of your air units from the map (chosen by you).",
          "Oligarchs Assert Power.\nUnless you have conquered and control two full economic zones beyond your initial borders (as of drawing this card), you must pay the oligarchs (the bank) 10 Francs the next time you conquer a new territory (after a successful invasion, during that combat phase).\nThis card lasts until canceled by some other card or the action is fulfilled.",
          "Assassin Hits Mark.\nFortunately, Mark is merely your twin brother.\nMilitary units in your home territories all participate in the hunt for the killer - and use one supply each (drawn from anywhere in your home territories; you choose).",
          "John has a Long Mustache.\nResistance fighters destroy railways in foreign territories occupied by you.\nFor the next turn, you may not move units or supplies by rail outside of your home territories.",
          "Resistance Proclaims Independence!\nA full economic zone outside your home territories, chosen randomly, becomes neutral and obtains 5 neutral infantry placed in some random territory of that province.\nThe League of Nations will vote for control of those armies immediately; it requires only 3 Francs total contribution to control.\nIf League fails to vote to secure the armies, remove both the neutral infantry and three of your own units in the economic zone from the board.",
          "Terrorism Damages Economy.\nAll economic zones lose one unit of added GDP (effective immediately).",
          "Ghetto Uprising!\nChoose randomly among cities you have captured.\nIf the city is garrisoned with either no units or only one unit, it proclaims neutrality and adds 3 infantry.\nThe League of Nations votes immediately for control.\nYour unit evacuates to an adjacent territory that you control (if impossible, your unit is lost).\nIf the League fails to provide 3 Francs, the freedom fighters disappear from the map.",
          "Guerilla\'s Plot to Aid Invaders.\nChoose a province randomly.\nWithin that province, Democracies draw one extra combat card in combats on this turn.",
          "Low Morale.\nEnlistees seek to dodge the draft.\nInfantry and armor costs increase by 1 Pound for this next allocation phase.",
          "Political Corruption Damages Your Supply Chain.\nIn every location you have ordered new supplies produced, 2 less supplies are actually produced than ordered in this turn.",
          "Weapons Program Corruption.\nYour nuclear scientists have been lying to you.\nYour nuclear progress is actually... 0, including any production ordered this turn.",
          "Work Camps Produce Poor Ammunition.\nSupplies cost 2 pounds this turn.",
          "Lack of Freedom Damages Economic Growth.\nRemove 1 (added) GDP point from all of your fully conquered economic zones.",
          "Obtain intelligence of uprising; spectacular show trials increase support.\nObtain 2 additional Francs.",
          "Political Generals Are Idiots.\nYour generals were appointed by their connections rather than by their merits.\nIn all land combats during the next turn, draw at most one combat card.",
          "Massive Supply Theft!\nRemove 5 supplies from your stocks currently on the board.\nWhile you shoot those responsible, unfortunately it is impossible to locate the lost goods.",
          "Low Infantry Morale.\nWith idiots like you in charge, the war is hopeless.\nWho wants to be the last to die in a lost cause?\nFully supplied infantry in the next turn fight at (1 attack, 2 defense); unsupplied infantry fight at (0 attack, 1 defense).",
          "Bagdad Bob.\nIf you have lost any of your starting territory, lose 10 Francs for the embarrassment."
          ]
        },
        democracy : {
          zero : [
          "No elections held this year.\nDomestic tranquility.\nObtain 3 Francs.",
          "Minor corruption trials related to weapons programs.\nLose 2 Francs to hush it up unless you had more atomic research (at the end of your previous turn) than any other player.",
          "Success buys tranquility.\nIf you have full possession of more economic zones than with which you began the game, obtain 1 Franc.\nOtherwise, lose 1 Franc.",
          "Retrospective voting.\nIf GDP increased over the turn, face no negative political consequences.\nOtherwise, pay 5 Francs.",
          "Peace dividends.\nIf you took no casualties over the last year, obtain 5 Francs.\nOtherwise, pay 5 Francs.",
          "Peace Party obtain majority.\nMilitary units abroad not returned within your original boundaries by the end of the following winter are disbanded.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists obtain majority.\nYour units may not fight in allied combinations with dictatorships for two full turns (display this card over that entire period; may be canceled by subsequent political cards).",
          "Anti-Imperialists demand recognition of national independence movements.\nAny territories acquired through the action of the league of nations on your part must be returned to independence and neutrality - including any units currently in those territories that belong to you.\nAllied units are evacuated to their nearest exit point or sold back to the bank for 1 Franc each.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year.",
          "Peace Party defeats defense budget.\nYou may not spend anything on military units, supplies, or atomic development in this upcoming turn.\nYou must spend 30% of your budget on politics.\nYou must spend as much as you can on economic development.\nAny unspent GDP (due to costs of development) is simply lost.",
          "Hawks defeat budget.\nYou must spend your entire budget on military units and supplies.",
          "Government gridlock.\nYou repeat your expenditures by category from the previous year (so, same amount for military units, supplies, politics, atomic research, and development).\nAnything not obtainable is lost.",
          "The Coburn Committee seeks to eliminate waste, fraud, and abuse; you may not make any political spending for the next turn.\nAdditionally, lose 5 Francs.",
          "Payoffs to Tammany Hall.\nSpend 50 percent of your GDP on politics to obtain the 30% outcome - or lose 20 Francs at the end of the next turn.\nKeep this card out (decide privately).",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 10 Francs per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 20 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Force Exit from League of Nations.\nYou may not participate in the League of Nations for the next two turns.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the remainder of the game, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the remainder of the game, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Independence Vote Successful.\nOne of your economic zones (other than those with which you began the game with full control), chosen at random, votes for independence.\nAll units, supplies, and development in that territory becomes part of an independent neutral country.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 1 in the next turn (if fully supplied) and a combat value of .5 if unsupplied.",
          "Anti-War Protestors prevent recruitment.\nAll infantry units slated to be produced this turn refuse to enlist and are disbanded."
          ],

          thirty : [
          "No elections held this year.\nObtain an additional 5 Francs.",
          "Form national government.\nIn the next political cycle, obtain 30% payout in Francs but retain the GDP and draw no political cards.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 5 additional Francs.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 1 Franc.",
          "Peace Dividends.\nIf you took no casualties over the last turn, obtain 10 additional Francs.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 3 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Propaganda Victory.\nFor every vote at the League of Nations this turn, each of your Francs counts as two.",
          "Anti-communists ask you to form dictatorship.\nObtain one-time payout of 15 Francs and then play the rest of the game as a dictator if you choose.\nOtherwise, obtain a one-time payout of 20 Francs.",
          "Peace Party defeats defense budget.\nYou may not purchase any armor or heavy fleets in this turn.",
          "Navy advocates insist on the construction of one heavy fleet.\nIf you pay 2 Francs now, you may produce the fleet at a 5 pound discount.\nIf you do not produce the fleet by the end of the next turn, pay 1 Franc.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.",
          "The Coburn Committee suspends operation because Senator Coburn dies of a heart attack.\nObtain 3 Francs.",
          "War enthusiasm lowers infantry and armor costs by 1 pound per unit this turn.",
          "Ross Sevy Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 1 Franc per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next turn, lose 5 Francs.",
          "Isolationists Wish to Exit from League of Nations.\nIf you leave the League of Nations for the next two turns, collect 5 Francs.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the next turn, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 1 Franc for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the next turn, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors shot by national guard.\nPay 1 Franc.",
          "Anti-War Protestors increase the cost of recruitment.\nInfantry and Armor units cost an additional pound this turn."
          ],

          twenty : [
          "No elections held this year.\nObtain an additional 3 Francs.",
          "Peace Party offers conditional support.\nIf in your last turn you purchased no additional atomic research, obtain 3 Francs.\nOtherwise, nothing happens.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 5 additional Francs.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 1 Franc.",
          "Peace Dividends.\nIf you took no casualties over the last turn, obtain 7 additional Francs.\nOtherwise, lose 1 Franc.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 3 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Propaganda Victory.\nFor every vote at the League of Nations this turn, each of your Francs counts as two.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year unless you pay 2 Francs for the turn (now).",
          "Peace Party defeats defense budget.\nYou may not purchase any armor or heavy fleets in this turn.",
          "Navy advocates insist on the construction of one heavy fleet.\nIf you do not comply, or cannot comply, lose 2 Francs.\nKeep this card on the table.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.",
          "The Coburn Committee finds waste, fraud, and abuse.\nYou may not spend more than 10% on politics in the next year and you must pay 4 Francs immediately to the bank.",
          "War enthusiasm lowers infantry cost by 1 pound per unit this turn.",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 1 Franc per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 10 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Wish to Exit from League of Nations.\nIf you leave the League of Nations for the next two turns, collect 5 Francs.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the next turn, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the next turn, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 2 in the next turn (if fully supplied) and a combat value of 1 if unsupplied.",
          "Anti-War Protestors increase the cost of recruitment.\nInfantry and Armor units cost an additional pound this turn."
          ],

          ten : [
          "No elections held this year.\nObtain an additional 3 Francs.",
          "Peace Party offers conditional support.\nIf in your last turn you purchased no additional atomic research, obtain 2 Francs.\nOtherwise, nothing happens.",
          "Military Success Bonus.\nIf your frontiers have expanded since the start of the game, obtain 1 additional Franc.",
          "Retrospective Voting.\nIf GDP increased over the last turn, obtain 5 additional Francs.\nIf not, lose 2 Francs.",
          "Peace Dividends.\nIf you took no casualties over the last tun, obtain 5 additional Francs.\nOtherwise, lose 2 Francs.",
          "Peace Party makes gains in legislature.\nIf combat took place over the last turn involving your units, pay 5 Francs.",
          "Isolationists obtain majority.\nYou may not attack the units of any power in the next turn unless you either\n(a) fought units of that power in this last turn or\n(b) are attacked by units of that power.",
          "Idealists make gains in legislature.\nYour units may not fight in allied combinations with dictatorships for one full turn unless you pay 1 Franc per combat season in which they fight.",
          "Anti-Imperialists demand recognition of national independence movements.\nAny territories acquired through the action of the league of nations on your part must be returned to independence and neutrality if the league votes on their independence and pays at least 1 Franc per unit in the territories.\nYour units and allied units are evacuated to their nearest exit point or sold back to the bank for 1 Franc each.",
          "Anti-communists gain a majority.\nYour units may not fight in conjunction in the next year with any Democracy or Dictatorship that spent more than 10% on politics in this year.",
          "Peace Party defeats defense budget.\nYou may not purchase any additional military units in the upcoming turn although you may purchase supplies.",
          "Hawks insist on the construction of two heavy fleets.\nYou must comply if your budget allows and you have port facilities.\nIf you do not have port facilities, pay 2 Francs.\nIf you have ports but your budget does not allow the construction of two heavy fleets, pay 5 Francs.",
          "Government gridlock.\nYou must produce precisely the same military units this year as you produced last year.",
          "The Coburn Committee finds waste, fraud, and abuse.\nYou may not spend more than 10% on politics in the next year and you must pay 4 Francs immediately to the bank.",
          "Payoffs to Tammany Hall.\nSpend 50 percent of your GDP on politics to obtain the 30% outcome - or lose 5 Francs at the end of the next turn.\nKeep this card out (decide privately).",
          "War Party Takes Control of Parliament.\nIf any of your territories are adjacent to a neutral territory, you must invade it or pay 3 Francs per combat season (paid once orders are revealed in that season) in which this action does not take place.",
          "Idealist Fanatics demand that the world be made safe for Democracy!\nIf you do not occupy a city of a foreign dictatorship within the next two turns (six combat seasons), lose 20 Francs.\nVoid if canceled by subsequent political card or the end of the game.\nKeep this card on the table.",
          "Isolationists Force Exit from League of Nations.\nYou may not participate in the League of Nations for the next two turns.\nKeep this card out on the table.",
          "Parliament Favors Internationalists.\nFor the remainder of the game, you may only invade a foreign country to conquer it with a majority vote in the League of Nations (vote taken after orders issued; if failed, orders do not execute and units defend).\nPay each nation, other than the one you are invading, 3 Francs for the privilege of holding the vote, regardless of the outcome.",
          "Parliament Favors League of Democracies.\nFor the remainder of the game, you may only initiate hostilities with a foreign power if all the Democracies unanimously consent.\nMust obtain consent after orders have been issued; if withheld, orders do not execute and units defend.",
          "Atomic Protestors Win Vote in Congress.\nAlthough you may develop the atomic bomb, you may not use it in this game.",
          "Dissatisfied Socialists Leak Secrets.\nOne nation is chosen at random: if you have more atomic research than they do, a spy brings their research up to your level.",
          "Surprise victory in a midterm election.\nYou may pay 1 Franc to remove the effects of any previous political card (of yours) currently operating against you.\nYou must decide now.",
          "Anti-War Protestors weaken army.\nAll armor and infantry units fight at a combat value of 1 in the next turn (if fully supplied) and a combat value of .5 if unsupplied.",
          "Anti-War Protestors prevent recruitment.\nAll infantry units slated to be produced this turn refuse to enlist and are disbanded."
          ]
        }
      }
    }
  )
}
